# Generated by Django 3.2.3 on 2021-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('describtion', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('genre', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=100)),
                ('year_of_issue', models.DecimalField(decimal_places=0, max_digits=4)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
